BlockchainMonitor.WebUI/Controllers/GraphicsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BlockchainMonitor.WebUI.Controllers
{
    public class GraphicsController : Controller
    {
        // GET: Graphics
        public ActionResult Index()
        {
            return View();
        }
    }
}

BlockchainMonitor.WebUI/Controllers/ParticipantsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BlockchainMonitor.WebUI.Controllers
{
    public class ParticipantsController : Controller
    {
        // GET: Participants
        public ActionResult Index()
        {
            return View();
        }
    }
}

BlockchainMonitor.WebUI/Controllers/SmartContractsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BlockchainMonitor.WebUI.Controllers
{
    public class SmartContractsController : Controller
    {
        // GET: SmartControllers
        public ActionResult Index()
        {
            return View();
        }
    }
}

BlockchainMonitor.WebUI/Controllers/StatisticsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BlockchainMonitor.WebUI.Controllers
{
    public class StatisticsController : Controller
    {
        // GET: Statistics
        public ActionResult Index()
        {
            return View();
        }
    }
}

BlockchainMonitor.WebUI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Мониторинг блокчейн базы данных</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body class="blockchain-body">
    <div class="navbar navbar-fixed-top blockchain-header-top">
        <div class="container">
            <div class="navbar-header blockchain-header">
                <button type="button" class="navbar-toggle blockchain-header-button" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Блокчейн монитор", "Index", "Home", new { area = "" }, new { @class = "navbar-brand blockchain-logo" })
            </div>
            <div class="navbar-collapse collapse blockchain-main-menu">
                <ul class="nav navbar-nav blockchain-main-menu-navbar">
                    <li>@Html.ActionLink("Главная", "Index", "Home", new { @class = "blockchain-menu-item"})</li>
                    <li>@Html.ActionLink("Графики", "Index", "Graphics", new { @class = "blockchain-menu-item" })</li>
                    <li>@Html.ActionLink("Статистика", "Index", "Statistics", new { @class = "blockchain-menu-item" })</li>
                    <li>@Html.ActionLink("Участники", "Index", "Participants", new { @class = "blockchain-menu-item" })</li>
                    <li>@Html.ActionLink("Смартконтракты", "Index", "SmartContracts", new { @class = "blockchain-menu-item" })</li>
                </ul>
                @Html.Partial("_Search")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <div class="pull-left">&copy; @DateTime.Now.Year - ДИТ г. Москвы</div>
            <div class="center-block">
                <span>@Html.ActionLink("О проекте", "About", "Home")</span>
                <span>@Html.ActionLink("Стать участником", "BecomeMember", "Home")</span>
                <span>@Html.ActionLink("API", "API", "Home")</span>
            </div>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/knockout")
    @Scripts.Render("~/bundles/signalr")
    @Scripts.Render("~/bundles/carousel")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

BlockchainMonitor.WebUI/Views/Shared/_ParticipantPartial.cshtml
@model BlockchainMonitor.WebUI.ViewModels.MainPage.ParticipantListVM
@using BlockchainMonitor.WebUI.ViewModels.MainPage
<!--offline-->
<div>
    <hr />
    <div class="clearfix">
        <h3 class="pull-left">@Model.Title</h3>
        <!--blocks navigation buttons-->
        <div class="pull-right">
            <div class="btn-group" role="group" aria-label="participants online">
                <button type="button" class="btn btn-default">
                    <span class="glyphicon glyphicon-menu-left" aria-hidden="true"></span>
                </button>
                <button type="button" class="btn btn-default">
                    <span class="glyphicon glyphicon-menu-right" aria-hidden="true"></span>
                </button>
            </div>
        </div>
    </div>
    <div class="all-participants clearfix">
        <!--ВЕРСТАЛЬЩИКУ: сделать эти блоки прокручиваемыми направо-->
        @foreach (ParticipantVM par in Model.Participants)
        {
            <div class="participant pull-left">
                <div class="participant-image">
                    <img src="@par.Icon" />
                </div>
                <div>
                    @par.NodesCount сервер(а)
                </div>
            </div>
        }
    </div>
    <div>
        @Html.ActionLink("Все участники", "Index", "Participants")
    </div>
</div>

BlockchainMonitor.WebUI/Views/Shared/_Search.cshtml
@using (@Html.BeginForm("SearchText", "Search", FormMethod.Post, new { id = "logoutForm", @class = "form-inline nav navbar-nav navbar-right blockchain-search-navbar" }))
{
    <div class="form-group blockchain-search">
        <div class="blockchain-search-container">
            <input type="text" class="form-control blockchain-search-input" id="searchblockchain" placeholder="Хеш / Идентификатор">
            <button type="submit" class="btn btn-default blockchain-search-button"></button>
        </div>
    </div>
}